-- CreateTable
CREATE TABLE "organizations" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "created_at" TEXT NOT NULL,

    CONSTRAINT "organizations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "administrators" (
    "id" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "password_hash" TEXT NOT NULL,
    "created_at" TEXT NOT NULL,

    CONSTRAINT "administrators_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "memberships" (
    "id" TEXT NOT NULL,
    "organization_id" TEXT NOT NULL,
    "administrator_id" TEXT NOT NULL,
    "role" TEXT NOT NULL,

    CONSTRAINT "memberships_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "admin_sessions" (
    "id" TEXT NOT NULL,
    "membership_id" TEXT NOT NULL,
    "token_hash" TEXT NOT NULL,
    "created_at" TEXT NOT NULL,
    "expires_at" TEXT NOT NULL,
    "revoked_at" TEXT,

    CONSTRAINT "admin_sessions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "audit_events" (
    "id" TEXT NOT NULL,
    "organization_id" TEXT,
    "kind" TEXT NOT NULL,
    "actor" TEXT NOT NULL,
    "detail" TEXT NOT NULL,
    "occurred_at" TEXT NOT NULL,
    "seq" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,

    CONSTRAINT "audit_events_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "instance_state" (
    "key" TEXT NOT NULL,
    "value" TEXT NOT NULL,

    CONSTRAINT "instance_state_pkey" PRIMARY KEY ("key")
);

-- CreateTable
CREATE TABLE "identities" (
    "id" TEXT NOT NULL,
    "organization_id" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "email_verified" INTEGER NOT NULL DEFAULT 0,
    "password_hash" TEXT NOT NULL,
    "created_at" TEXT NOT NULL,
    "sessions_revoked_at" TEXT,
    "suspended_at" TEXT,
    "anonymized_at" TEXT,

    CONSTRAINT "identities_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "identity_tokens" (
    "id" TEXT NOT NULL,
    "identity_id" TEXT NOT NULL,
    "kind" TEXT NOT NULL,
    "token_hash" TEXT NOT NULL,
    "expires_at" TEXT NOT NULL,
    "consumed_at" TEXT,
    "created_at" TEXT NOT NULL,

    CONSTRAINT "identity_tokens_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "administrator_invitations" (
    "id" TEXT NOT NULL,
    "organization_id" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "role" TEXT NOT NULL,
    "token_hash" TEXT NOT NULL,
    "invited_by" TEXT NOT NULL,
    "expires_at" TEXT NOT NULL,
    "consumed_at" TEXT,
    "expiry_audited_at" TEXT,
    "created_at" TEXT NOT NULL,

    CONSTRAINT "administrator_invitations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "applications" (
    "id" TEXT NOT NULL,
    "organization_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "client_id" TEXT NOT NULL,
    "created_by" TEXT NOT NULL,
    "created_at" TEXT NOT NULL,
    "disabled_at" TEXT,
    "deleted_at" TEXT,
    "allowed_scopes" TEXT NOT NULL DEFAULT 'openid email profile',

    CONSTRAINT "applications_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "client_secrets" (
    "id" TEXT NOT NULL,
    "application_id" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "secret_hash" TEXT NOT NULL,
    "created_by" TEXT NOT NULL,
    "created_at" TEXT NOT NULL,
    "revoked_at" TEXT,
    "revoked_by" TEXT,

    CONSTRAINT "client_secrets_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "redirect_uris" (
    "id" TEXT NOT NULL,
    "application_id" TEXT NOT NULL,
    "uri" TEXT NOT NULL,
    "created_by" TEXT NOT NULL,
    "created_at" TEXT NOT NULL,
    "updated_by" TEXT,
    "updated_at" TEXT,

    CONSTRAINT "redirect_uris_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "enrollments" (
    "id" TEXT NOT NULL,
    "identity_id" TEXT NOT NULL,
    "application_id" TEXT NOT NULL,
    "created_at" TEXT NOT NULL,
    "suspended_at" TEXT,

    CONSTRAINT "enrollments_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "sessions" (
    "id" TEXT NOT NULL,
    "identity_id" TEXT NOT NULL,
    "organization_id" TEXT NOT NULL,
    "sso_token_hash" TEXT NOT NULL,
    "user_agent" TEXT,
    "created_at" TEXT NOT NULL,
    "last_seen_at" TEXT NOT NULL,
    "expires_at" TEXT NOT NULL,
    "revoked_at" TEXT,

    CONSTRAINT "sessions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "authorization_codes" (
    "id" TEXT NOT NULL,
    "code_hash" TEXT NOT NULL,
    "application_id" TEXT NOT NULL,
    "identity_id" TEXT NOT NULL,
    "session_id" TEXT NOT NULL,
    "redirect_uri" TEXT NOT NULL,
    "scope" TEXT NOT NULL,
    "code_challenge" TEXT,
    "code_challenge_method" TEXT,
    "nonce" TEXT,
    "created_at" TEXT NOT NULL,
    "expires_at" TEXT NOT NULL,
    "consumed_at" TEXT,

    CONSTRAINT "authorization_codes_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "refresh_tokens" (
    "id" TEXT NOT NULL,
    "token_hash" TEXT NOT NULL,
    "session_id" TEXT NOT NULL,
    "application_id" TEXT NOT NULL,
    "identity_id" TEXT NOT NULL,
    "scope" TEXT NOT NULL,
    "created_at" TEXT NOT NULL,
    "expires_at" TEXT NOT NULL,
    "rotated_at" TEXT,
    "revoked_at" TEXT,

    CONSTRAINT "refresh_tokens_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "organization_settings" (
    "organization_id" TEXT NOT NULL,
    "key" TEXT NOT NULL,
    "value" TEXT NOT NULL,
    "updated_by" TEXT,
    "updated_at" TEXT NOT NULL,

    CONSTRAINT "organization_settings_pkey" PRIMARY KEY ("organization_id","key")
);

-- CreateTable
CREATE TABLE "email_change_requests" (
    "id" TEXT NOT NULL,
    "organization_id" TEXT NOT NULL,
    "identity_id" TEXT NOT NULL,
    "new_email" TEXT NOT NULL,
    "token_hash" TEXT NOT NULL,
    "expires_at" TEXT NOT NULL,
    "consumed_at" TEXT,
    "created_at" TEXT NOT NULL,

    CONSTRAINT "email_change_requests_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "administrators_email_key" ON "administrators"("email");

-- CreateIndex
CREATE UNIQUE INDEX "memberships_organization_id_administrator_id_key" ON "memberships"("organization_id", "administrator_id");

-- CreateIndex
CREATE UNIQUE INDEX "admin_sessions_token_hash_key" ON "admin_sessions"("token_hash");

-- CreateIndex
CREATE UNIQUE INDEX "audit_events_seq_key" ON "audit_events"("seq");

-- CreateIndex
CREATE INDEX "audit_events_organization_time_idx" ON "audit_events"("organization_id", "occurred_at");

-- CreateIndex
CREATE UNIQUE INDEX "identities_organization_id_email_key" ON "identities"("organization_id", "email");

-- CreateIndex
CREATE UNIQUE INDEX "identity_tokens_token_hash_key" ON "identity_tokens"("token_hash");

-- CreateIndex
CREATE UNIQUE INDEX "administrator_invitations_token_hash_key" ON "administrator_invitations"("token_hash");

-- CreateIndex
CREATE UNIQUE INDEX "applications_client_id_key" ON "applications"("client_id");

-- CreateIndex
CREATE UNIQUE INDEX "client_secrets_secret_hash_key" ON "client_secrets"("secret_hash");

-- CreateIndex
CREATE UNIQUE INDEX "redirect_uris_application_id_uri_key" ON "redirect_uris"("application_id", "uri");

-- CreateIndex
CREATE UNIQUE INDEX "enrollments_identity_id_application_id_key" ON "enrollments"("identity_id", "application_id");

-- CreateIndex
CREATE UNIQUE INDEX "sessions_sso_token_hash_key" ON "sessions"("sso_token_hash");

-- CreateIndex
CREATE UNIQUE INDEX "authorization_codes_code_hash_key" ON "authorization_codes"("code_hash");

-- CreateIndex
CREATE UNIQUE INDEX "refresh_tokens_token_hash_key" ON "refresh_tokens"("token_hash");

-- CreateIndex
CREATE INDEX "refresh_tokens_session_idx" ON "refresh_tokens"("session_id");

-- CreateIndex
CREATE INDEX "refresh_tokens_application_idx" ON "refresh_tokens"("application_id");

-- CreateIndex
CREATE UNIQUE INDEX "email_change_requests_token_hash_key" ON "email_change_requests"("token_hash");

-- CreateIndex
CREATE INDEX "email_change_requests_identity_idx" ON "email_change_requests"("identity_id");

-- AddForeignKey
ALTER TABLE "memberships" ADD CONSTRAINT "memberships_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "memberships" ADD CONSTRAINT "memberships_administrator_id_fkey" FOREIGN KEY ("administrator_id") REFERENCES "administrators"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "admin_sessions" ADD CONSTRAINT "admin_sessions_membership_id_fkey" FOREIGN KEY ("membership_id") REFERENCES "memberships"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "audit_events" ADD CONSTRAINT "audit_events_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "identities" ADD CONSTRAINT "identities_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "identity_tokens" ADD CONSTRAINT "identity_tokens_identity_id_fkey" FOREIGN KEY ("identity_id") REFERENCES "identities"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "administrator_invitations" ADD CONSTRAINT "administrator_invitations_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "administrator_invitations" ADD CONSTRAINT "administrator_invitations_invited_by_fkey" FOREIGN KEY ("invited_by") REFERENCES "administrators"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "applications" ADD CONSTRAINT "applications_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "applications" ADD CONSTRAINT "applications_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "administrators"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "client_secrets" ADD CONSTRAINT "client_secrets_application_id_fkey" FOREIGN KEY ("application_id") REFERENCES "applications"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "client_secrets" ADD CONSTRAINT "client_secrets_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "administrators"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "client_secrets" ADD CONSTRAINT "client_secrets_revoked_by_fkey" FOREIGN KEY ("revoked_by") REFERENCES "administrators"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "redirect_uris" ADD CONSTRAINT "redirect_uris_application_id_fkey" FOREIGN KEY ("application_id") REFERENCES "applications"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "redirect_uris" ADD CONSTRAINT "redirect_uris_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "administrators"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "redirect_uris" ADD CONSTRAINT "redirect_uris_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "administrators"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "enrollments" ADD CONSTRAINT "enrollments_identity_id_fkey" FOREIGN KEY ("identity_id") REFERENCES "identities"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "enrollments" ADD CONSTRAINT "enrollments_application_id_fkey" FOREIGN KEY ("application_id") REFERENCES "applications"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_identity_id_fkey" FOREIGN KEY ("identity_id") REFERENCES "identities"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "authorization_codes" ADD CONSTRAINT "authorization_codes_application_id_fkey" FOREIGN KEY ("application_id") REFERENCES "applications"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "authorization_codes" ADD CONSTRAINT "authorization_codes_identity_id_fkey" FOREIGN KEY ("identity_id") REFERENCES "identities"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "authorization_codes" ADD CONSTRAINT "authorization_codes_session_id_fkey" FOREIGN KEY ("session_id") REFERENCES "sessions"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "refresh_tokens" ADD CONSTRAINT "refresh_tokens_session_id_fkey" FOREIGN KEY ("session_id") REFERENCES "sessions"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "refresh_tokens" ADD CONSTRAINT "refresh_tokens_application_id_fkey" FOREIGN KEY ("application_id") REFERENCES "applications"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "refresh_tokens" ADD CONSTRAINT "refresh_tokens_identity_id_fkey" FOREIGN KEY ("identity_id") REFERENCES "identities"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "organization_settings" ADD CONSTRAINT "organization_settings_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "organization_settings" ADD CONSTRAINT "organization_settings_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "administrators"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "email_change_requests" ADD CONSTRAINT "email_change_requests_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "email_change_requests" ADD CONSTRAINT "email_change_requests_identity_id_fkey" FOREIGN KEY ("identity_id") REFERENCES "identities"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- Hand-written constraints below this line. The Prisma schema language cannot
-- express CHECK constraints (ADR-0027), so these are invisible to it and must
-- be carried in migrations by hand. Future generated migrations must be
-- reviewed so they never silently drop them.

-- Email normalization guards. Application code stores handles trimmed and
-- Unicode-lowercased (ADR-0005); these checks are the database-level backstop
-- and remain permanently, including after native types land in Stage 2.
ALTER TABLE "administrators" ADD CONSTRAINT "administrators_email_normalized_check" CHECK ("email" = lower("email"));
ALTER TABLE "identities" ADD CONSTRAINT "identities_email_normalized_check" CHECK ("email" = lower("email"));
ALTER TABLE "administrator_invitations" ADD CONSTRAINT "administrator_invitations_email_normalized_check" CHECK ("email" = lower("email"));
ALTER TABLE "email_change_requests" ADD CONSTRAINT "email_change_requests_new_email_normalized_check" CHECK ("new_email" = lower("new_email"));

-- Legacy storage-shape guards (Stage 1 only). Stage 2 replaces each of these
-- encodings with a native PostgreSQL type or enum and drops the check with it.
ALTER TABLE "identities" ADD CONSTRAINT "identities_email_verified_check" CHECK ("email_verified" IN (0, 1));
ALTER TABLE "memberships" ADD CONSTRAINT "memberships_role_check" CHECK ("role" IN ('owner', 'member'));
ALTER TABLE "identity_tokens" ADD CONSTRAINT "identity_tokens_kind_check" CHECK ("kind" IN ('email_verification', 'password_reset'));
ALTER TABLE "administrator_invitations" ADD CONSTRAINT "administrator_invitations_role_check" CHECK ("role" IN ('owner', 'member'));
ALTER TABLE "applications" ADD CONSTRAINT "applications_type_check" CHECK ("type" IN ('web', 'spa'));
ALTER TABLE "organization_settings" ADD CONSTRAINT "organization_settings_key_check" CHECK ("key" IN ('branding', 'password_policy', 'session_policy'));
